window.alert(`Hacking... █`);
window.alert(`Hacking... ██`);
window.alert(`Hacking... ███`);
window.alert(`Hacking... ████`);
window.alert(`Hacking... █████`);
window.alert(`Hacking... ██████`);
window.alert(`Hacking... ███████`);
window.alert(`Hacking... ████████`);
window.alert(`Hacking... █████████`);
window.alert(`Hacking... ██████████`);
window.alert(`Hacking... ███████████`);
window.alert(`Hacking... ████████████`);
window.alert(`Hacking... █████████████`);
window.alert(`Hacking... ██████████████`);
window.alert(`Hacking... ███████████████`);
window.alert(`Hacking... █████████████████████████`);
window.alert(`Hacking... ███████████████████████████████████`);
window.alert(`DONE...`);

window.alert(`You have been hacked`);
window.alert(`I have full access to your computer`);
window.alert(`Subscribe to this YouTube channel or I will delete all your files`);
window.alert(`https://youtube.com/@i_developer`);
